### ISSUE TITLE
SyntaxError: invalid syntax when import corintick libary

### ISSUE THREAD

**Issue by liuenda** [plugaai/corintick#2]
When I run:
import corintick

This error message appears:

Traceback (most recent call last):
  File "unittest/unittest_HDS_price_data_handler.py", line 20, in <module>
    from TR_historical_look_up.HDS_price_data_handler import HDSPriceLoader
  File "/home/liu/Workplace/project-3/market_price_data_handler/TR_historical_look_up/__init__.py", line 1, in <module>
    from .TR_price_data_handler import TRPriceLoader
  File "/home/liu/Workplace/project-3/market_price_data_handler/TR_historical_look_up/TR_price_data_handler.py", line 17, in <module>
    from corintick import Corintick
  File "/home/liu/miniconda3/envs/py3k/lib/python3.5/site-packages/corintick/__init__.py", line 1, in <module>
    from .corintick import Corintick
  File "/home/liu/miniconda3/envs/py3k/lib/python3.5/site-packages/corintick/corintick.py", line 74
    self.logger.warning(f'The following requested columns were not found: {not_found}')
                                                                                     ^

**SyntaxError: invalid syntax**

Hope you can fix it. 
Thank you very much

**Comment by liuenda** [comment]
Finally, it seems the problem could be solved by updating my python version from 3.5 to 3.6.
